<?php

declare(strict_types=1);

namespace App\Modules\Audit\Models;

use App\Support\HasPublicId;
use Database\Factories\AuditLogFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use RuntimeException;

/** APPEND ONLY. An audit trail that can be edited is not one. */
/**
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property string $actor_type
 * @property int|null $actor_id
 * @property string $action
 * @property string|null $subject_type
 * @property int|null $subject_id
 * @property array<string, mixed>|null $changes
 * @property string|null $reason
 * @property string|null $ip_address
 * @property Carbon $created_at
 */
final class AuditLog extends Model
{
    /** @use HasFactory<AuditLogFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'audit_logs';

    public $timestamps = false;

    protected $fillable = [
        'actor_type', 'actor_id', 'action', 'subject_type', 'subject_id',
        'changes', 'reason', 'ip_address', 'created_at',
    ];

    protected function casts(): array
    {
        return ['changes' => 'array', 'created_at' => 'datetime'];
    }

    protected static function booted(): void
    {
        self::updating(function (): never {
            throw new RuntimeException('audit_logs is append-only.');
        });

        self::deleting(function (): never {
            throw new RuntimeException('audit_logs is append-only.');
        });
    }
}
