<?php

declare(strict_types=1);

namespace App\Modules\Orders\Models;

use Database\Factories\OrderStatusHistoryFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use RuntimeException;

/** APPEND ONLY. Every transition is its own row with an actor. */
/**
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property int|null $seller_order_id
 * @property int|null $marketplace_order_id
 * @property string|null $from_status
 * @property string $to_status
 * @property string $actor_type
 * @property int|null $actor_id
 * @property string|null $note
 * @property Carbon|null $created_at
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 * @property int $id
 * @property int|null $seller_order_id
 * @property int|null $marketplace_order_id
 * @property string|null $from_status
 * @property string $to_status
 * @property string $actor_type
 * @property int|null $actor_id
 * @property string|null $note
 * @property Carbon|null $created_at
 */
final class OrderStatusHistory extends Model
{
    /** @use HasFactory<OrderStatusHistoryFactory> */
    use HasFactory;

    protected $table = 'order_status_history';

    public $timestamps = false;

    protected $fillable = [
        'seller_order_id', 'marketplace_order_id', 'from_status', 'to_status',
        'actor_type', 'actor_id', 'note', 'created_at',
    ];

    protected function casts(): array
    {
        return ['created_at' => 'datetime'];
    }

    protected static function booted(): void
    {
        self::updating(function (): never {
            throw new RuntimeException('order_status_history is append-only.');
        });

        self::deleting(function (): never {
            throw new RuntimeException('order_status_history is append-only.');
        });
    }
}
