<?php

declare(strict_types=1);

namespace App\Modules\Orders\Models;

use App\Modules\Orders\Enums\ShipmentStatus;
use App\Support\HasPublicId;
use Database\Factories\ShipmentFactory;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Carbon;
use RuntimeException;

/**
 * One parcel, and exactly what is in it.
 *
 * A seller order ships in as many of these as it takes. That is the whole
 * reason the aggregate exists: with a carrier and a tracking number on the
 * seller order instead, an order of three items shipped in two boxes has
 * nowhere to record the second box, and the customer is told the wrong
 * thing about both.
 *
 * Not append-only — a parcel legitimately moves from draft to shipped to
 * delivered — but every move is written to shipment_status_history first,
 * and nothing may leave a delivered or cancelled shipment except through
 * an explicit, permissioned override.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property string $reference
 * @property int $seller_order_id
 * @property int $sequence
 * @property ShipmentStatus $status
 * @property string|null $carrier_name
 * @property string|null $carrier_code
 * @property string|null $tracking_number
 * @property string|null $tracking_url
 * @property Carbon|null $packed_at
 * @property Carbon|null $shipped_at
 * @property Carbon|null $delivered_at
 * @property Carbon|null $cancelled_at
 * @property string|null $created_by_type
 * @property int|null $created_by_id
 * @property string|null $notes
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read Collection<int, ShipmentItem> $items
 * @property-read SellerOrder|null $sellerOrder
 */
final class Shipment extends Model
{
    /** @use HasFactory<ShipmentFactory> */
    use HasFactory;

    use HasPublicId;

    /** What happened, and when. Never rewritten by a later correction. */
    public const IMMUTABLE_COLUMNS = ['seller_order_id', 'reference', 'sequence'];

    protected $table = 'shipments';

    protected $fillable = [
        'seller_order_id', 'reference', 'sequence', 'status',
        'carrier_name', 'carrier_code', 'tracking_number', 'tracking_url',
        'packed_at', 'shipped_at', 'delivered_at', 'cancelled_at',
        'created_by_type', 'created_by_id', 'notes',
    ];

    protected function casts(): array
    {
        return [
            'status' => ShipmentStatus::class,
            'sequence' => 'integer',
            'packed_at' => 'datetime',
            'shipped_at' => 'datetime',
            'delivered_at' => 'datetime',
            'cancelled_at' => 'datetime',
        ];
    }

    protected static function booted(): void
    {
        self::updating(function (self $shipment): void {
            foreach (self::IMMUTABLE_COLUMNS as $column) {
                if ($shipment->isDirty($column)) {
                    throw new RuntimeException(
                        "shipments.{$column} is immutable. A parcel belongs to one seller order ".
                        'under one reference for its whole life.'
                    );
                }
            }
        });

        self::deleting(function (): never {
            throw new RuntimeException(
                'A shipment is cancelled, never deleted: a customer was told it existed.'
            );
        });
    }

    /** @return HasMany<ShipmentItem, $this> */
    public function items(): HasMany
    {
        return $this->hasMany(ShipmentItem::class);
    }

    /** @return BelongsTo<SellerOrder, $this> */
    public function sellerOrder(): BelongsTo
    {
        return $this->belongsTo(SellerOrder::class);
    }

    /** @return HasMany<ShipmentStatusHistory, $this> */
    public function history(): HasMany
    {
        return $this->hasMany(ShipmentStatusHistory::class);
    }

    /** Total units in the parcel. */
    public function unitCount(): int
    {
        return (int) $this->items->sum('quantity');
    }
}
