<?php

declare(strict_types=1);

namespace App\Modules\Orders\Models;

use App\Support\HasPublicId;
use Database\Factories\ShipmentFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $seller_order_id
 * @property string $carrier
 * @property string|null $carrier_code
 * @property string $tracking_number
 * @property Carbon $shipped_at
 * @property Carbon|null $delivered_at
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 */
final class Shipment extends Model
{
    /** @use HasFactory<ShipmentFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'shipments';

    protected $fillable = [
        'seller_order_id', 'carrier', 'carrier_code', 'tracking_number',
        'shipped_at', 'delivered_at',
    ];

    protected function casts(): array
    {
        return ['shipped_at' => 'datetime', 'delivered_at' => 'datetime'];
    }
}
