<?php

declare(strict_types=1);

namespace App\Modules\Inventory\Models;

use App\Modules\Inventory\Data\StockLevel;
use App\Modules\Inventory\Enums\ReservationStatus;
use App\Modules\Inventory\Enums\StockState;
use App\Modules\Offers\Models\Offer;
use Database\Factories\InventoryBalanceFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * The physical count for one offer at one location.
 *
 * Both quantities change only through a movement, and `available` is a
 * generated column: the database subtracts, so no reader can arrive at a
 * different number. Nothing here writes `available`, and nothing should —
 * PostgreSQL rejects it.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property int $offer_id
 * @property int $inventory_location_id
 * @property int $on_hand
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property int $reserved
 * @property int|null $available
 * @property string|null $notified_state
 * @property Carbon|null $notified_at
 * @property-read Offer|null $offer
 */
final class InventoryBalance extends Model
{
    /** @use HasFactory<InventoryBalanceFactory> */
    use HasFactory;

    protected $table = 'inventory_balances';

    // `available` is deliberately absent: it is generated, and a mass
    // assignment naming it is an error rather than a no-op.
    protected $fillable = ['offer_id', 'inventory_location_id', 'on_hand', 'reserved'];

    /**
     * Mirrors the schema's own defaults.
     *
     * Without these a freshly created row reads `reserved` as null until
     * it is refreshed, and every quantity computed from it becomes null
     * too. `available` stays out: it is generated, so the only honest
     * value for it before a read is "ask the database".
     */
    protected $attributes = [
        'on_hand' => 0,
        'reserved' => 0,
    ];

    protected function casts(): array
    {
        return [
            'on_hand' => 'integer',
            'reserved' => 'integer',
            'available' => 'integer',
            'notified_at' => 'datetime',
        ];
    }

    /** @return BelongsTo<Offer, $this> */
    public function offer(): BelongsTo
    {
        return $this->belongsTo(Offer::class);
    }

    /**
     * The live holds, summed from the reservation rows themselves.
     *
     * This is the reconciliation source, not the read path: `reserved` is
     * the column everything else uses, and `inventory:reconcile` asserts
     * the two agree. Keeping the slow version is what makes the fast one
     * trustworthy.
     */
    public function heldByReservations(): int
    {
        return (int) InventoryReservation::query()
            ->where('offer_id', $this->offer_id)
            ->where('inventory_location_id', $this->inventory_location_id)
            ->where('status', ReservationStatus::Held->value)
            ->sum('quantity');
    }

    /**
     * The threshold that applies here: the offer's own, else the store's
     * default, else the platform's.
     *
     * Zero is a decision — no low-stock warning wanted — and null is the
     * absence of one, which is why neither level uses zero as its default.
     */
    public function lowStockThreshold(): int
    {
        $offer = $this->offer;

        // `??` has isset semantics, so a missing offer or store falls
        // through the chain rather than dereferencing null.
        return $offer->low_stock_threshold
            ?? $offer->store->default_low_stock_threshold
            ?? (int) config('veritas.inventory.low_stock_threshold');
    }

    /** The one representation every surface reads. */
    public function level(): StockLevel
    {
        return StockLevel::of($this->on_hand, $this->reserved, $this->lowStockThreshold());
    }

    public function state(): StockState
    {
        return $this->level()->state;
    }
}
