<?php

declare(strict_types=1);

namespace App\Modules\Inventory\Models;

use App\Modules\Inventory\Enums\ReservationStatus;
use App\Support\HasPublicId;
use Database\Factories\InventoryReservationFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $offer_id
 * @property int $inventory_location_id
 * @property int $quantity
 * @property ReservationStatus $status
 * @property string|null $reference
 * @property int|null $marketplace_order_id
 * @property Carbon|null $expires_at
 * @property Carbon|null $resolved_at
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 */
final class InventoryReservation extends Model
{
    /** @use HasFactory<InventoryReservationFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'inventory_reservations';

    protected $fillable = [
        'offer_id',
        'inventory_location_id',
        'quantity',
        'status',
        'reference',
        'marketplace_order_id',
        'expires_at',
        'resolved_at',
    ];

    protected function casts(): array
    {
        return [
            'status' => ReservationStatus::class,
            'quantity' => 'integer',
            'expires_at' => 'datetime',
            'resolved_at' => 'datetime',
        ];
    }

    public function isExpired(): bool
    {
        return $this->expires_at !== null && $this->expires_at->isPast();
    }
}
