<?php

declare(strict_types=1);

namespace App\Modules\Offers\Models;

use App\Modules\Catalog\Models\Product;
use App\Modules\Catalog\Models\ProductVariant;
use App\Modules\Inventory\Models\InventoryBalance;
use App\Modules\Offers\Enums\OfferStatus;
use App\Modules\Sellers\Concerns\BelongsToSellerAccount;
use App\Modules\Sellers\Models\SellerAccount;
use App\Modules\Stores\Models\Store;
use App\Support\HasPublicId;
use App\Support\Money;
use Database\Factories\OfferFactory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Carbon;

/**
 * A seller's commercial listing against a canonical product variant.
 *
 * This is what a customer buys. It carries price, condition, stock and
 * fulfilment terms; the product carries identity.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $seller_account_id
 * @property int $store_id
 * @property int $product_id
 * @property int|null $product_variant_id
 * @property string $seller_sku
 * @property string $condition
 * @property int $price_minor
 * @property int|null $compare_at_price_minor
 * @property string $currency
 * @property OfferStatus $status
 * @property string|null $moderation_reason
 * @property Carbon|null $published_at
 * @property Carbon|null $archived_at
 * @property int $handling_days
 * @property int|null $shipping_flat_minor
 * @property int|null $free_shipping_threshold_minor
 * @property string|null $seller_notes
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read Product|null $product
 * @property-read ProductVariant|null $productVariant
 * @property-read SellerAccount|null $sellerAccount
 * @property-read Store|null $store
 * @property-read Collection<int, InventoryBalance> $inventoryBalances
 */
final class Offer extends Model
{
    use BelongsToSellerAccount;

    /** @use HasFactory<OfferFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'offers';

    protected $fillable = [
        'seller_account_id',
        'store_id',
        'product_id',
        'product_variant_id',
        'seller_sku',
        'condition',
        'price_minor',
        'compare_at_price_minor',
        'currency',
        'status',
        'handling_days',
        'shipping_flat_minor',
        'free_shipping_threshold_minor',
        'seller_notes',
    ];

    protected function casts(): array
    {
        return [
            'status' => OfferStatus::class,
            'price_minor' => 'integer',
            'compare_at_price_minor' => 'integer',
            'published_at' => 'datetime',
            'archived_at' => 'datetime',
        ];
    }

    /** @return BelongsTo<Product, $this> */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    /** @return BelongsTo<ProductVariant, $this> */
    public function productVariant(): BelongsTo
    {
        return $this->belongsTo(ProductVariant::class);
    }

    /** @return BelongsTo<SellerAccount, $this> */
    public function sellerAccount(): BelongsTo
    {
        return $this->belongsTo(SellerAccount::class);
    }

    /** @return BelongsTo<Store, $this> */
    public function store(): BelongsTo
    {
        return $this->belongsTo(Store::class);
    }

    /** @return HasMany<InventoryBalance, $this> */
    public function inventoryBalances(): HasMany
    {
        return $this->hasMany(InventoryBalance::class);
    }

    public function price(): Money
    {
        return Money::of($this->price_minor, $this->currency);
    }

    public function compareAtPrice(): ?Money
    {
        return $this->compare_at_price_minor === null
            ? null
            : Money::of($this->compare_at_price_minor, $this->currency);
    }

    public function isPurchasable(): bool
    {
        return $this->status->isPurchasable();
    }

    /** @param  Builder<Offer>  $query */
    public function scopePurchasable(Builder $query): void
    {
        $query->where('status', OfferStatus::Published->value);
    }
}
