<?php

declare(strict_types=1);

namespace Tests\Support\Failure;

use PHPUnit\Framework\Attributes\Test;
use ReflectionClass;
use ReflectionMethod;
use Tests\Feature\Failure\DatabaseOutageTest;
use Tests\Feature\Failure\DegradedServiceTest;
use Tests\Feature\Failure\FinancialWriteOutageTest;
use Tests\Feature\Failure\LoggingFailureTest;
use Tests\Feature\Failure\MailFailureTest;
use Tests\Feature\Failure\ObjectStorageFailureTest;
use Tests\Feature\Failure\QueueOutageTest;
use Tests\Feature\Failure\RedisOutageTest;
use Tests\Feature\Failure\SchedulerOutageTest;
use Tests\Feature\Failure\TransactionRollbackTest;
use Tests\Invariants\QueueRetryPolicyTest;

/**
 * The failure matrix, read out of the drills.
 *
 * Every row is a test that runs. The scenario column is the drill's own
 * name, the expectation is the first sentence of its docblock, and the
 * grouping is the class — so the document cannot describe a behaviour
 * nobody checks, and cannot omit one that somebody added.
 *
 * What it deliberately does not do is invent prose. If a drill has no
 * docblock the row says so, which is a more useful document than one
 * where the missing explanations are invisible.
 */
final class FailureMatrix
{
    /** The drill classes, in the order the matrix reads best. */
    private const CLASSES = [
        DatabaseOutageTest::class => 'PostgreSQL unavailable — read path',
        FinancialWriteOutageTest::class => 'PostgreSQL unavailable — financial writes',
        TransactionRollbackTest::class => 'Failure inside a transaction',
        RedisOutageTest::class => 'Redis unavailable — cache and post-commit dispatch',
        QueueOutageTest::class => 'Redis unavailable — webhook intake and recovery',
        MailFailureTest::class => 'Mail provider failing',
        ObjectStorageFailureTest::class => 'Object storage failing',
        DegradedServiceTest::class => 'Payment provider, SSR and derived projections',
        SchedulerOutageTest::class => 'Scheduler stopped',
        LoggingFailureTest::class => 'Logging or local disk failing',
        QueueRetryPolicyTest::class => 'Retry and backoff policy',
    ];

    public static function render(): string
    {
        $lines = [
            '# Failure matrix',
            '',
            'Generated by `php tools/failure-matrix.php` from the drills in',
            '`tests/Feature/Failure` and `tests/Invariants/QueueRetryPolicyTest`. Every row below is a test',
            'that runs in the ordinary suite; a scenario that is added, removed or renamed changes this',
            'document or fails `--check`.',
            '',
            'The drills take dependencies away for real where there is something to take away —',
            'PostgreSQL and Redis are removed by pointing the application at a closed port, so the',
            'driver raises the exception production would raise. Mail and object storage have no local',
            'endpoint to unplug and get controlled fakes that fail at the same seam. Failures *inside* a',
            'transaction are injected through the query log, because every action here is `final` with a',
            'typed constructor and a substituted collaborator is refused by PHP before the transaction',
            'even opens.',
            '',
            'Nothing in `app/` knows any of this exists. There is no production failure switch.',
            '',
        ];

        $total = 0;

        foreach (self::CLASSES as $class => $heading) {
            $reflection = new ReflectionClass($class);
            $tests = self::testsOf($class);
            $total += count($tests);

            $lines[] = '## '.$heading;
            $lines[] = '';
            $lines[] = '`'.$reflection->getShortName().'`';
            $lines[] = '';
            $lines[] = '| Scenario | Proven behaviour |';
            $lines[] = '| --- | --- |';

            foreach ($tests as $name => $expectation) {
                $lines[] = sprintf('| %s | %s |', self::humanise($name), $expectation);
            }

            $lines[] = '';
        }

        $lines[] = '---';
        $lines[] = '';
        $lines[] = sprintf('%d drills across %d areas.', $total, count(self::CLASSES));
        $lines[] = '';

        return implode("\n", $lines)."\n";
    }

    /**
     * @param  class-string  $class
     * @return array<string, string> test method name => first sentence of its docblock
     */
    private static function testsOf(string $class): array
    {
        $tests = [];

        foreach ((new ReflectionClass($class))->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
            if ($method->getDeclaringClass()->getName() !== $class) {
                continue;
            }

            if ($method->getAttributes(Test::class) === []) {
                continue;
            }

            $tests[$method->getName()] = self::summaryOf((string) $method->getDocComment());
        }

        return $tests;
    }

    /**
     * The first sentence of a docblock, or an honest admission.
     *
     * Deliberately not a fallback to the method name: a row that repeats
     * its own scenario in both columns looks documented and says nothing.
     */
    private static function summaryOf(string $docblock): string
    {
        $text = preg_replace('/^\s*\/\*\*|\s*\*\/$/m', '', $docblock) ?? '';
        $text = preg_replace('/^\s*\*\s?/m', '', $text) ?? '';
        $text = trim((string) preg_replace('/\s+/', ' ', $text));

        if ($text === '') {
            return '_(no description on the drill)_';
        }

        $end = mb_strpos($text, '. ');

        return $end === false ? $text : mb_substr($text, 0, $end + 1);
    }

    private static function humanise(string $method): string
    {
        return ucfirst(str_replace('_', ' ', $method));
    }
}
