<?php

declare(strict_types=1);

namespace App\Modules\Media\Contracts;

use App\Modules\Media\Data\StoredObject;
use App\Modules\Media\Enums\Visibility;
use App\Modules\Media\Exceptions\RejectedUpload;
use Illuminate\Http\UploadedFile;

/**
 * The storage port.
 *
 * Domain code depends on this and never on a provider SDK. The production
 * target is S3-compatible object storage; development uses a local disk;
 * neither is named anywhere outside the binding, so swapping one for the
 * other changes configuration rather than code.
 *
 * Keys are generated by the implementation, never supplied by a caller and
 * never derived from an uploader's filename.
 */
interface ObjectStore
{
    /**
     * Store an uploaded file and return where it went.
     *
     * @param  string  $collection  A path prefix describing what this is, e.g. "products/42/images"
     *
     * @throws RejectedUpload when the file is not acceptable
     */
    public function put(UploadedFile $file, string $collection, Visibility $visibility): StoredObject;

    /** Store raw bytes — used by processing jobs writing derivatives. */
    public function putContents(
        string $contents,
        string $collection,
        string $mime,
        Visibility $visibility,
    ): StoredObject;

    /**
     * A durable public URL, for objects that have one.
     *
     * Private objects do not: ask for a temporary URL, or stream them
     * through a controller that checks authorisation first.
     */
    public function url(StoredObject $object): string;

    /**
     * A signed, expiring URL, or null when the disk cannot produce one.
     *
     * Null is not a failure — a local disk legitimately cannot sign — and
     * the caller is expected to fall back to streaming the bytes itself.
     */
    public function temporaryUrl(StoredObject $object, int $seconds): ?string;

    /** @return resource|null */
    public function readStream(StoredObject $object);

    public function exists(StoredObject $object): bool;

    public function delete(StoredObject $object): void;

    /** Parse the `disk:key` form back into a reference. */
    public function fromReference(string $reference, Visibility $visibility): StoredObject;
}
