<?php

declare(strict_types=1);

namespace App\Modules\Catalog\Models;

use App\Modules\Catalog\Enums\AttributeType;
use App\Support\HasPublicId;
use Database\Factories\AttributeFactory;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Carbon;

/**
 * A specification a product can carry: storage, colour, screen size.
 *
 * Defined once for the whole catalogue and assigned to the categories that
 * want it, so "Colour" means the same thing on a phone and on a jacket and
 * a filter can span both.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property string $code
 * @property string $name
 * @property string|null $description
 * @property AttributeType $data_type
 * @property string|null $unit
 * @property bool $is_filterable
 * @property bool $is_searchable
 * @property bool $is_variant_defining
 * @property int $position
 * @property bool $is_active
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read Collection<int, AttributeOption> $options
 * @property-read Collection<int, Category> $categories
 */
final class Attribute extends Model
{
    /** @use HasFactory<AttributeFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'attributes';

    protected $fillable = [
        'code', 'name', 'description', 'data_type', 'unit',
        'is_filterable', 'is_searchable', 'is_variant_defining',
        'position', 'is_active',
    ];

    protected function casts(): array
    {
        return [
            'data_type' => AttributeType::class,
            'is_filterable' => 'boolean',
            'is_searchable' => 'boolean',
            'is_variant_defining' => 'boolean',
            'is_active' => 'boolean',
        ];
    }

    /** @return HasMany<AttributeOption, $this> */
    public function options(): HasMany
    {
        return $this->hasMany(AttributeOption::class)->orderBy('position');
    }

    /** @return BelongsToMany<Category, $this> */
    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Category::class, 'category_attributes')
            ->withPivot(['is_required', 'is_variant_defining', 'position'])
            ->withTimestamps();
    }

    /**
     * Whether the category assignments currently loaded make this
     * attribute mandatory.
     *
     * Meaningful only after Category::effectiveAttributes() has loaded
     * `categories` constrained to one lineage: a child category's own
     * assignment is what makes an inherited attribute required, so any
     * loaded pivot saying so is enough.
     */
    public function isRequiredByLoadedCategories(): bool
    {
        return $this->categories->contains(
            static fn (Category $category): bool => (bool) $category->getAttribute('pivot')?->getAttribute('is_required'),
        );
    }

    /** Whether a given value is one this attribute permits. */
    public function permits(string $value): bool
    {
        if (! $this->data_type->isEnumerated()) {
            return true;
        }

        return $this->options()->where('value', $value)->exists();
    }
}
