<?php

declare(strict_types=1);

namespace App\Modules\Catalog\Models;

use App\Support\HasPublicId;
use Database\Factories\BrandFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property string $name
 * @property string $slug
 * @property int|null $owner_seller_account_id
 * @property int|null $merged_into_brand_id
 * @property bool $is_active
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 * @property int $id
 * @property string $public_id
 * @property string $name
 * @property string $slug
 * @property int|null $owner_seller_account_id
 * @property int|null $merged_into_brand_id
 * @property bool $is_active
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 */
final class Brand extends Model
{
    /** @use HasFactory<BrandFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'brands';

    protected $fillable = ['name', 'slug', 'owner_seller_account_id', 'merged_into_brand_id', 'is_active'];

    protected function casts(): array
    {
        return ['is_active' => 'boolean'];
    }

    /** Platform-wide brands may be used by any seller; owned ones may not. */
    public function isSelectableBy(int $sellerAccountId): bool
    {
        return $this->owner_seller_account_id === null
            || $this->owner_seller_account_id === $sellerAccountId;
    }
}
