<?php

declare(strict_types=1);

namespace App\Modules\Catalog\Models;

use App\Modules\Catalog\Enums\AttributeType;
use Database\Factories\ProductAttributeValueFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * One product's answer to one attribute.
 *
 * The value lives in the column matching its type, which is what keeps
 * "phones with 256GB storage" an indexable query instead of a scan through
 * JSON documents.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property int $product_id
 * @property int $attribute_id
 * @property int|null $product_variant_id
 * @property string|null $value_text
 * @property int|null $value_int
 * @property string|null $value_decimal
 * @property bool|null $value_boolean
 * @property Carbon|null $value_date
 * @property int|null $attribute_option_id
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read Product|null $product
 * @property-read Attribute|null $attribute
 * @property-read ProductVariant|null $productVariant
 * @property-read AttributeOption|null $option
 */
final class ProductAttributeValue extends Model
{
    /** @use HasFactory<ProductAttributeValueFactory> */
    use HasFactory;

    protected $table = 'product_attribute_values';

    protected $fillable = [
        'product_id', 'attribute_id', 'product_variant_id',
        'value_text', 'value_int', 'value_decimal', 'value_boolean',
        'value_date', 'attribute_option_id',
    ];

    protected function casts(): array
    {
        return [
            'value_int' => 'integer',
            'value_boolean' => 'boolean',
            'value_date' => 'date',
        ];
    }

    /** @return BelongsTo<Product, $this> */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    /** @return BelongsTo<Attribute, $this> */
    public function attribute(): BelongsTo
    {
        return $this->belongsTo(Attribute::class);
    }

    /** @return BelongsTo<ProductVariant, $this> */
    public function productVariant(): BelongsTo
    {
        return $this->belongsTo(ProductVariant::class);
    }

    /** @return BelongsTo<AttributeOption, $this> */
    public function option(): BelongsTo
    {
        return $this->belongsTo(AttributeOption::class, 'attribute_option_id');
    }

    /**
     * The value as a person would read it, unit included.
     *
     * Presentation deliberately lives with the value rather than in a
     * component: a specification table, a filter chip and a variant label
     * must all render "256 GB" the same way.
     */
    /**
     * The value as it was entered, for putting back in a form field.
     *
     * Not display(): a unit appended to a number is for reading, and
     * feeding it back into an input would grow one every time the seller
     * saved.
     */
    public function raw(): string
    {
        $attribute = $this->attribute;

        if ($attribute === null) {
            return '';
        }

        return match ($attribute->data_type) {
            AttributeType::Text => (string) $this->value_text,
            AttributeType::Integer => (string) $this->value_int,
            AttributeType::Decimal => rtrim(rtrim((string) $this->value_decimal, '0'), '.'),
            AttributeType::Boolean => $this->value_boolean ? '1' : '0',
            AttributeType::Date => (string) $this->value_date?->toDateString(),
            AttributeType::Select, AttributeType::MultiSelect => (string) $this->option?->value,
        };
    }

    public function display(): string
    {
        $attribute = $this->attribute;

        if ($attribute === null) {
            return '';
        }

        $value = match ($attribute->data_type) {
            AttributeType::Text => (string) $this->value_text,
            AttributeType::Integer => (string) $this->value_int,
            AttributeType::Decimal => rtrim(rtrim((string) $this->value_decimal, '0'), '.'),
            AttributeType::Boolean => $this->value_boolean ? 'Yes' : 'No',
            AttributeType::Date => (string) $this->value_date?->toFormattedDateString(),
            AttributeType::Select, AttributeType::MultiSelect => (string) $this->option?->label,
        };

        return $attribute->unit === null || $value === ''
            ? $value
            : $value.' '.$attribute->unit;
    }
}
