<?php

declare(strict_types=1);

namespace App\Modules\Catalog\Models;

use App\Modules\Media\Enums\Visibility;
use App\Support\HasPublicId;
use Database\Factories\ProductMediaFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * An image belonging to a canonical product.
 *
 * Product photography is public and full colour — the monochrome of the
 * design system is chrome, never the goods. Processing runs on a queue, so
 * a row exists before its derivatives do, and `processing_state` says
 * which.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property int $product_id
 * @property string $path
 * @property int $position
 * @property bool $is_primary
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property string|null $public_id
 * @property int|null $product_variant_id
 * @property string $disk
 * @property string|null $mime
 * @property int $bytes
 * @property int|null $width
 * @property int|null $height
 * @property string|null $checksum
 * @property string|null $alt_text
 * @property string $processing_state
 * @property Carbon|null $processed_at
 * @property-read Product|null $product
 * @property-read ProductVariant|null $productVariant
 */
final class ProductMedia extends Model
{
    /** @use HasFactory<ProductMediaFactory> */
    use HasFactory;

    use HasPublicId;

    public const STATE_PENDING = 'pending';

    public const STATE_READY = 'ready';

    public const STATE_FAILED = 'failed';

    protected $table = 'product_media';

    protected $fillable = [
        'product_id', 'product_variant_id', 'disk', 'path', 'mime', 'bytes',
        'width', 'height', 'checksum', 'alt_text', 'position', 'is_primary',
        'processing_state', 'processed_at',
    ];

    protected function casts(): array
    {
        return [
            'is_primary' => 'boolean',
            'bytes' => 'integer',
            'width' => 'integer',
            'height' => 'integer',
            'processed_at' => 'datetime',
        ];
    }

    /** @return BelongsTo<Product, $this> */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    /** @return BelongsTo<ProductVariant, $this> */
    public function productVariant(): BelongsTo
    {
        return $this->belongsTo(ProductVariant::class);
    }

    /** The `disk:key` form the object store understands. */
    public function reference(): string
    {
        return $this->disk.':'.$this->path;
    }

    public function visibility(): Visibility
    {
        return Visibility::Public;
    }

    public function isReady(): bool
    {
        return $this->processing_state === self::STATE_READY;
    }
}
