<?php

declare(strict_types=1);

namespace App\Modules\Catalog\Models;

use App\Support\HasPublicId;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;
use RuntimeException;

/**
 * One step in a product's moderation history.
 *
 * Append-only: the record of who proposed a product, who reviewed it and
 * what they said is the provenance of a catalogue entry the marketplace
 * now owns, and rewriting it would make that ownership unauditable.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $product_id
 * @property string|null $from_status
 * @property string $to_status
 * @property string $actor_type
 * @property int|null $actor_id
 * @property string|null $reason
 * @property Carbon $created_at
 * @property-read Product|null $product
 */
final class ProductProposalEvent extends Model
{
    use HasPublicId;

    protected $table = 'product_proposal_events';

    public $timestamps = false;

    protected $fillable = [
        'product_id', 'from_status', 'to_status', 'actor_type', 'actor_id', 'reason', 'created_at',
    ];

    protected function casts(): array
    {
        return ['created_at' => 'datetime'];
    }

    protected static function booted(): void
    {
        self::updating(function (): never {
            throw new RuntimeException('product_proposal_events is append-only.');
        });

        self::deleting(function (): never {
            throw new RuntimeException('product_proposal_events is append-only.');
        });
    }

    /** @return BelongsTo<Product, $this> */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }
}
