<?php

declare(strict_types=1);

namespace App\Modules\Sellers\Models;

use App\Modules\Sellers\Enums\SellerApplicationStatus;
use App\Support\HasPublicId;
use Database\Factories\SellerApplicationFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * One form, three sections, no wizard — multi-step onboarding is abandoned.
 *
 * Re-applying edits this record rather than creating a duplicate, so the
 * APP- reference is stable across attempts and a rejection reason stays
 * attached to the history.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property string $reference
 * @property int $user_id
 * @property string $legal_name
 * @property string $trading_name
 * @property string $business_type
 * @property string $tax_id
 * @property string $address_line1
 * @property string|null $address_line2
 * @property string $address_city
 * @property string $address_state
 * @property string $address_postcode
 * @property string $address_country
 * @property string $contact_name
 * @property string|null $contact_role
 * @property string $contact_email
 * @property string|null $contact_phone
 * @property int|null $primary_category_id
 * @property int|null $planned_listings
 * @property string|null $existing_site
 * @property string|null $blurb
 * @property SellerApplicationStatus $status
 * @property Carbon|null $terms_accepted_at
 * @property Carbon|null $decided_at
 * @property int|null $decided_by_admin_id
 * @property string|null $decision_reason
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 * @property int $id
 * @property string $public_id
 * @property string $reference
 * @property int $user_id
 * @property string $legal_name
 * @property string $trading_name
 * @property string $business_type
 * @property string $tax_id
 * @property string $address_line1
 * @property string|null $address_line2
 * @property string $address_city
 * @property string $address_state
 * @property string $address_postcode
 * @property string $address_country
 * @property string $contact_name
 * @property string|null $contact_role
 * @property string $contact_email
 * @property string|null $contact_phone
 * @property int|null $primary_category_id
 * @property int|null $planned_listings
 * @property string|null $existing_site
 * @property string|null $blurb
 * @property SellerApplicationStatus $status
 * @property Carbon|null $terms_accepted_at
 * @property Carbon|null $decided_at
 * @property int|null $decided_by_admin_id
 * @property string|null $decision_reason
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 */
final class SellerApplication extends Model
{
    /** @use HasFactory<SellerApplicationFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'seller_applications';

    protected $fillable = [
        'reference', 'user_id', 'legal_name', 'trading_name', 'business_type', 'tax_id',
        'address_line1', 'address_line2', 'address_city', 'address_state',
        'address_postcode', 'address_country', 'contact_name', 'contact_role',
        'contact_email', 'contact_phone', 'primary_category_id', 'planned_listings',
        'existing_site', 'blurb', 'status', 'terms_accepted_at',
    ];

    protected function casts(): array
    {
        return [
            'status' => SellerApplicationStatus::class,
            'tax_id' => 'encrypted',
            'terms_accepted_at' => 'datetime',
            'decided_at' => 'datetime',
        ];
    }
}
