<?php

declare(strict_types=1);

namespace App\Modules\Sellers\Models;

use App\Support\HasPublicId;
use Database\Factories\SellerApplicationDocumentFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * A verification document attached to an application.
 *
 * The path is generated, never the uploader's filename, and the disk is
 * recorded alongside it so the file can be found after the platform moves
 * from a local disk to object storage.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $seller_application_id
 * @property string $kind
 * @property string $disk
 * @property string $path
 * @property string $original_name
 * @property string $mime
 * @property int $bytes
 * @property string|null $checksum
 * @property Carbon $uploaded_at
 */
final class SellerApplicationDocument extends Model
{
    /** @use HasFactory<SellerApplicationDocumentFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'seller_application_documents';

    public $timestamps = false;

    protected $fillable = [
        'seller_application_id', 'kind', 'disk', 'path', 'original_name',
        'mime', 'bytes', 'checksum', 'uploaded_at',
    ];

    protected function casts(): array
    {
        return ['uploaded_at' => 'datetime', 'bytes' => 'integer'];
    }
}
