<?php

declare(strict_types=1);

namespace App\Modules\Sellers\Models;

use App\Support\HasPublicId;
use Database\Factories\SellerApplicationEventFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use RuntimeException;

/** APPEND ONLY. The decision history of one application. */
/**
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $seller_application_id
 * @property string|null $from_status
 * @property string $to_status
 * @property string $actor_type
 * @property int|null $actor_id
 * @property string|null $reason
 * @property Carbon $created_at
 */
final class SellerApplicationEvent extends Model
{
    /** @use HasFactory<SellerApplicationEventFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'seller_application_events';

    public $timestamps = false;

    protected $fillable = [
        'seller_application_id', 'from_status', 'to_status',
        'actor_type', 'actor_id', 'reason', 'created_at',
    ];

    protected function casts(): array
    {
        return ['created_at' => 'datetime'];
    }

    protected static function booted(): void
    {
        self::updating(function (): never {
            throw new RuntimeException('seller_application_events is append-only.');
        });

        self::deleting(function (): never {
            throw new RuntimeException('seller_application_events is append-only.');
        });
    }
}
