<?php

declare(strict_types=1);

namespace App\Modules\Sellers\Models;

use App\Modules\Sellers\Enums\InvitationStatus;
use App\Modules\Sellers\Enums\SellerRole;
use App\Support\HasPublicId;
use Database\Factories\SellerInvitationFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * An invitation to join a seller organisation.
 *
 * Only the token's hash is stored: the plaintext exists in the email and
 * nowhere else, so a leaked table cannot be used to join someone's store.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $seller_account_id
 * @property string $email
 * @property SellerRole $role
 * @property string $token_hash
 * @property InvitationStatus $status
 * @property int|null $invited_by_user_id
 * @property int|null $accepted_by_user_id
 * @property Carbon $expires_at
 * @property Carbon|null $accepted_at
 * @property Carbon|null $revoked_at
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read SellerAccount|null $sellerAccount
 */
final class SellerInvitation extends Model
{
    /** @use HasFactory<SellerInvitationFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'seller_invitations';

    protected $fillable = [
        'seller_account_id', 'email', 'role', 'token_hash', 'status',
        'invited_by_user_id', 'accepted_by_user_id', 'expires_at',
        'accepted_at', 'revoked_at',
    ];

    protected $hidden = ['token_hash'];

    protected function casts(): array
    {
        return [
            'status' => InvitationStatus::class,
            'role' => SellerRole::class,
            'expires_at' => 'datetime',
            'accepted_at' => 'datetime',
            'revoked_at' => 'datetime',
        ];
    }

    /** @return BelongsTo<SellerAccount, $this> */
    public function sellerAccount(): BelongsTo
    {
        return $this->belongsTo(SellerAccount::class);
    }

    /** Live means pending and not yet past its deadline. */
    public function isRedeemable(): bool
    {
        return $this->status->isRedeemable() && $this->expires_at->isFuture();
    }

    public function hasExpired(): bool
    {
        return $this->expires_at->lessThanOrEqualTo(Carbon::now());
    }
}
