<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * The PostgreSQL search adapter's storage.
 *
 * A denormalised document per product with a generated tsvector, which is
 * enough for a catalogue of this size and costs no new infrastructure. It
 * sits behind the SearchIndex interface, so replacing it with a dedicated
 * engine in M3 is a binding change and nothing more.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('product_search_documents', function (Blueprint $table): void {
            $table->foreignId('product_id')->primary()->constrained()->cascadeOnDelete();

            $table->string('title');
            $table->string('brand_name')->nullable();
            $table->string('category_path')->nullable();
            $table->text('searchable_text');

            // Denormalised so a results page can sort and filter without
            // joining back to offers for every row.
            $table->boolean('is_public')->default(false);
            $table->bigInteger('lowest_price_minor')->nullable();
            $table->unsignedInteger('offer_count')->default(0);

            $table->timestamp('indexed_at');
        });

        // Generated by Postgres from searchable_text, so it cannot fall out
        // of step with the column it summarises.
        DB::statement(
            "alter table product_search_documents
             add column search_vector tsvector
             generated always as (to_tsvector('english', searchable_text)) stored"
        );

        DB::statement('create index product_search_documents_vector on product_search_documents using gin (search_vector)');
        DB::statement('create index product_search_documents_public on product_search_documents (is_public, lowest_price_minor)');
    }

    public function down(): void
    {
        Schema::dropIfExists('product_search_documents');
    }
};
