<?php

declare(strict_types=1);

namespace App\Modules\Payouts\Models;

use App\Modules\Payouts\Enums\SettlementAttemptStatus;
use App\Support\HasPublicId;
use App\Support\Money;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;
use RuntimeException;

/**
 * One attempt to actually move the money.
 *
 * Append-only, because a failed attempt is evidence. §66: a retry that
 * overwrote the previous failure would leave finance unable to answer "has
 * this seller been sent money twice", which is the exact question a
 * settlement-attempt table exists to answer.
 *
 * Phase 1 writes one row per payout, recorded by a person after they made
 * a transfer. A future provider adapter writes one per API call against the
 * same columns, and correlates a webhook back to this row by
 * `external_reference` — which is why that column is here now rather than
 * later.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $payout_request_id
 * @property string $provider
 * @property string|null $method
 * @property string|null $external_reference
 * @property SettlementAttemptStatus $status
 * @property string $currency
 * @property int $amount_minor
 * @property Carbon $initiated_at
 * @property Carbon|null $completed_at
 * @property string|null $failure_code
 * @property string|null $failure_message
 * @property int|null $initiated_by_admin_id
 * @property-read PayoutRequest|null $payoutRequest
 */
final class PayoutSettlementAttempt extends Model
{
    use HasPublicId;

    protected $table = 'payout_settlement_attempts';

    public $timestamps = false;

    protected $fillable = [
        'payout_request_id', 'provider', 'method', 'external_reference',
        'status', 'currency', 'amount_minor', 'initiated_at', 'completed_at',
        'failure_code', 'failure_message', 'initiated_by_admin_id',
    ];

    protected function casts(): array
    {
        return [
            'status' => SettlementAttemptStatus::class,
            'amount_minor' => 'integer',
            'initiated_at' => 'datetime',
            'completed_at' => 'datetime',
        ];
    }

    protected static function booted(): void
    {
        self::deleting(function (): never {
            throw new RuntimeException(
                'payout_settlement_attempts is append-only: a failed attempt is the record that it was tried.'
            );
        });
    }

    /** @return BelongsTo<PayoutRequest, $this> */
    public function payoutRequest(): BelongsTo
    {
        return $this->belongsTo(PayoutRequest::class);
    }

    public function amount(): Money
    {
        return Money::of($this->amount_minor, $this->currency);
    }
}
