<?php

declare(strict_types=1);

namespace App\Modules\Payouts\Models;

use App\Modules\Payouts\Enums\PayoutStatus;
use App\Modules\Sellers\Concerns\BelongsToSellerAccount;
use App\Modules\Sellers\Models\SellerAccount;
use App\Support\HasPublicId;
use App\Support\Money;
use Database\Factories\PayoutRequestFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Carbon;
use RuntimeException;

/**
 * A seller asking for money, and everything that happened to the request.
 *
 * The amount and currency are fixed at the moment it is made and may never
 * change: a request whose amount could be edited is not a request, it is a
 * negotiation, and the allocations holding money against it would no
 * longer add up. Everything else on the row is lifecycle — who reviewed
 * it, when it was approved, how it was settled.
 *
 * The destination is stored twice on purpose. `payout_account_id` points
 * at the live record, for anything that needs to follow it; the
 * `destination_*` snapshot says what the seller chose at the time, and is
 * what every screen displays. §58: a seller who changes their payout
 * details must not thereby change where an already-approved payout says it
 * was going.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property string $reference
 * @property int $seller_account_id
 * @property int|null $payout_account_id
 * @property string|null $destination_label
 * @property string|null $destination_type
 * @property string|null $seller_name_snapshot
 * @property string $currency
 * @property int $amount_minor
 * @property PayoutStatus $status
 * @property Carbon $requested_at
 * @property int|null $requested_by_user_id
 * @property Carbon|null $reviewed_at
 * @property int|null $reviewed_by_admin_id
 * @property Carbon|null $approved_at
 * @property int|null $approved_by_admin_id
 * @property Carbon|null $paid_at
 * @property int|null $settled_by_admin_id
 * @property Carbon|null $cancelled_at
 * @property Carbon|null $failed_at
 * @property Carbon|null $decided_at
 * @property int|null $decided_by_admin_id
 * @property string|null $decision_reason
 * @property string|null $settlement_ref
 * @property string|null $settlement_method
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read SellerAccount|null $sellerAccount
 * @property-read PayoutAccount|null $payoutAccount
 */
final class PayoutRequest extends Model
{
    use BelongsToSellerAccount;

    /** @use HasFactory<PayoutRequestFactory> */
    use HasFactory;

    use HasPublicId;

    /** What was asked for. Fixed at the moment of asking. */
    public const IMMUTABLE_COLUMNS = [
        'reference', 'seller_account_id', 'currency', 'amount_minor', 'requested_at',
    ];

    protected $table = 'payout_requests';

    protected $fillable = [
        'reference', 'seller_account_id', 'payout_account_id',
        'destination_label', 'destination_type', 'seller_name_snapshot',
        'currency', 'amount_minor', 'status', 'requested_at', 'requested_by_user_id',
        'reviewed_at', 'reviewed_by_admin_id', 'approved_at', 'approved_by_admin_id',
        'paid_at', 'settled_by_admin_id', 'cancelled_at', 'failed_at',
        'decided_at', 'decided_by_admin_id', 'decision_reason',
        'settlement_ref', 'settlement_method',
    ];

    protected function casts(): array
    {
        return [
            'status' => PayoutStatus::class,
            'amount_minor' => 'integer',
            'requested_at' => 'datetime',
            'reviewed_at' => 'datetime',
            'approved_at' => 'datetime',
            'paid_at' => 'datetime',
            'cancelled_at' => 'datetime',
            'failed_at' => 'datetime',
            'decided_at' => 'datetime',
        ];
    }

    protected static function booted(): void
    {
        self::updating(function (self $request): void {
            foreach (self::IMMUTABLE_COLUMNS as $column) {
                if ($request->isDirty($column)) {
                    throw new RuntimeException(
                        "payout_requests.{$column} is immutable. ".
                        'Reject this request and let the seller make another.'
                    );
                }
            }
        });

        // §26: a cancelled request is cancelled, not gone. Deleting one
        // would take its allocations and its history with it.
        self::deleting(function (): never {
            throw new RuntimeException('payout_requests is never deleted; cancel or reject the request instead.');
        });
    }

    /** @return BelongsTo<SellerAccount, $this> */
    public function sellerAccount(): BelongsTo
    {
        return $this->belongsTo(SellerAccount::class);
    }

    /** @return BelongsTo<PayoutAccount, $this> */
    public function payoutAccount(): BelongsTo
    {
        return $this->belongsTo(PayoutAccount::class);
    }

    /** @return HasMany<PayoutAllocation, $this> */
    public function allocations(): HasMany
    {
        return $this->hasMany(PayoutAllocation::class);
    }

    /** @return HasMany<PayoutSettlementAttempt, $this> */
    public function settlementAttempts(): HasMany
    {
        return $this->hasMany(PayoutSettlementAttempt::class);
    }

    /** @return HasMany<PayoutStatusHistory, $this> */
    public function history(): HasMany
    {
        return $this->hasMany(PayoutStatusHistory::class);
    }

    public function amount(): Money
    {
        return Money::of($this->amount_minor, $this->currency);
    }

    /** The label shown wherever this payout is displayed, snapshot first. */
    public function destinationLabel(): string
    {
        return $this->destination_label ?? 'Recorded manually by the platform';
    }
}
