<?php

declare(strict_types=1);

namespace App\Modules\Payouts\Models;

use App\Modules\Payouts\Enums\PayoutAccountType;
use App\Modules\Sellers\Concerns\BelongsToSellerAccount;
use App\Support\HasPublicId;
use Database\Factories\PayoutAccountFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * Where a seller's money goes, without holding the keys to it.
 *
 * Nothing on this record can be used to move money by itself. The label is
 * for a person to recognise, the last four digits are for the same reason
 * a card is shown as ****4242, and `provider_account_reference` is an
 * identifier a provider issued — meaningless without that provider's own
 * credentials, which live in configuration and never in a row.
 *
 * That is a deliberate limit, not an oversight. Phase 1 settles manually,
 * so the platform does not need to hold anything that could move money on
 * its own; when a provider rail is added it will hold a reference to an
 * account the provider verified, which is still not a credential.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $seller_account_id
 * @property PayoutAccountType $type
 * @property string $provider
 * @property string|null $provider_account_reference
 * @property string $display_label
 * @property string|null $last4
 * @property string|null $country
 * @property string $currency
 * @property string $status
 * @property Carbon|null $verified_at
 * @property Carbon|null $changed_at
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 */
final class PayoutAccount extends Model
{
    use BelongsToSellerAccount;

    /** @use HasFactory<PayoutAccountFactory> */
    use HasFactory;

    use HasPublicId;

    public const STATUS_ACTIVE = 'active';

    public const STATUS_DISABLED = 'disabled';

    protected $table = 'payout_accounts';

    protected $fillable = [
        'seller_account_id', 'type', 'provider', 'provider_account_reference',
        'display_label', 'last4', 'country', 'currency', 'status',
        'verified_at', 'changed_at',
    ];

    protected function casts(): array
    {
        return [
            'type' => PayoutAccountType::class,
            'verified_at' => 'datetime',
            'changed_at' => 'datetime',
        ];
    }

    public function isActive(): bool
    {
        return $this->status === self::STATUS_ACTIVE;
    }

    /**
     * The label copied onto a payout request at the moment it is made.
     *
     * §57 and §58: a payout read next year must still say where it went,
     * and changing this record afterwards must not rewrite that answer.
     */
    public function snapshotLabel(): string
    {
        return $this->last4 === null
            ? $this->display_label
            : $this->display_label.' ····'.$this->last4;
    }
}
