<?php

declare(strict_types=1);

namespace App\Modules\Payouts\Models;

use App\Modules\Payouts\Enums\PayoutAllocationStatus;
use App\Modules\Sellers\Concerns\BelongsToSellerAccount;
use App\Support\HasPublicId;
use App\Support\Money;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;
use RuntimeException;

/**
 * A claim on part of one earning, on behalf of one payout request.
 *
 * This is the reservation. While an allocation is HELD its amount is out
 * of the seller's withdrawable balance; when the payout settles it becomes
 * SETTLED and the ledger debit takes over; when the request is rejected or
 * cancelled it becomes RELEASED and the money is withdrawable again.
 *
 * Amounts never change — only the status does, and only forwards. An
 * allocation that turned out to be wrong is released and a new request is
 * made, because the whole point of holding money in rows rather than in a
 * running total is that you can go back and see what was held and when.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $payout_request_id
 * @property int $seller_ledger_entry_id
 * @property int $seller_account_id
 * @property string $currency
 * @property int $amount_minor
 * @property PayoutAllocationStatus $status
 * @property Carbon $created_at
 * @property Carbon|null $settled_at
 * @property Carbon|null $released_at
 * @property-read PayoutRequest|null $payoutRequest
 */
final class PayoutAllocation extends Model
{
    use BelongsToSellerAccount;
    use HasPublicId;

    /** What was held, and against what. None of it may be rewritten. */
    public const IMMUTABLE_COLUMNS = [
        'payout_request_id', 'seller_ledger_entry_id',
        'seller_account_id', 'currency', 'amount_minor', 'created_at',
    ];

    protected $table = 'payout_allocations';

    public $timestamps = false;

    protected $fillable = [
        'payout_request_id', 'seller_ledger_entry_id', 'seller_account_id',
        'currency', 'amount_minor', 'status', 'created_at', 'settled_at', 'released_at',
    ];

    protected function casts(): array
    {
        return [
            'status' => PayoutAllocationStatus::class,
            'amount_minor' => 'integer',
            'created_at' => 'datetime',
            'settled_at' => 'datetime',
            'released_at' => 'datetime',
        ];
    }

    protected static function booted(): void
    {
        self::updating(function (self $allocation): void {
            foreach (self::IMMUTABLE_COLUMNS as $column) {
                if ($allocation->isDirty($column)) {
                    throw new RuntimeException(
                        "payout_allocations.{$column} is immutable. ".
                        'Release the allocation and make a new request instead.'
                    );
                }
            }
        });

        self::deleting(function (): never {
            throw new RuntimeException(
                'payout_allocations is append-only: release an allocation, never delete it.'
            );
        });
    }

    /** @return BelongsTo<PayoutRequest, $this> */
    public function payoutRequest(): BelongsTo
    {
        return $this->belongsTo(PayoutRequest::class);
    }

    public function amount(): Money
    {
        return Money::of($this->amount_minor, $this->currency);
    }
}
