<?php

declare(strict_types=1);

namespace App\Modules\Reviews\Models;

use App\Modules\Catalog\Models\Product;
use App\Modules\Reviews\Enums\ReviewStatus;
use App\Support\HasPublicId;
use Database\Factories\ProductReviewFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Carbon;
use RuntimeException;

/**
 * One customer's review of one canonical product.
 *
 * The product, the customer and the purchase it rests on are fixed at
 * creation. What may change is the rating, the words, and the status —
 * the first two because a customer may reconsider, the third because a
 * moderator may act. A review whose product could be reassigned would be
 * a review of something the customer never bought.
 *
 * `verified_purchase` is IMMUTABLE, and that is the load-bearing part of
 * this file. It is derived on the server from the order at the moment the
 * review is written (see ReviewEligibility) and can never be set, edited
 * or supplied by a client afterwards. A marketplace whose verified badge
 * can be talked into existence has no verified badge.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $product_id
 * @property int $user_id
 * @property int|null $order_item_id
 * @property int|null $seller_order_id
 * @property int $rating
 * @property string|null $title
 * @property string $body
 * @property ReviewStatus $status
 * @property bool $verified_purchase
 * @property Carbon|null $published_at
 * @property Carbon|null $hidden_at
 * @property Carbon|null $rejected_at
 * @property Carbon|null $withdrawn_at
 * @property string|null $moderation_reason
 * @property int|null $moderated_by_admin_id
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read Product|null $product
 */
final class ProductReview extends Model
{
    /** @use HasFactory<ProductReviewFactory> */
    use HasFactory;

    use HasPublicId;

    /** What this review is about and what it rests on. None of it may move. */
    public const IMMUTABLE_COLUMNS = [
        'product_id', 'user_id', 'order_item_id', 'seller_order_id',
        'verified_purchase', 'created_at',
    ];

    protected $table = 'product_reviews';

    protected $fillable = [
        'product_id', 'user_id', 'order_item_id', 'seller_order_id',
        'rating', 'title', 'body', 'status', 'verified_purchase',
        'published_at', 'hidden_at', 'rejected_at', 'withdrawn_at',
        'moderation_reason', 'moderated_by_admin_id',
    ];

    protected function casts(): array
    {
        return [
            'status' => ReviewStatus::class,
            'rating' => 'integer',
            'verified_purchase' => 'boolean',
            'published_at' => 'datetime',
            'hidden_at' => 'datetime',
            'rejected_at' => 'datetime',
            'withdrawn_at' => 'datetime',
        ];
    }

    protected static function booted(): void
    {
        self::updating(function (self $review): void {
            foreach (self::IMMUTABLE_COLUMNS as $column) {
                if ($review->isDirty($column)) {
                    throw new RuntimeException(
                        "product_reviews.{$column} is immutable. ".
                        'A review is about one product, by one customer, on one purchase.'
                    );
                }
            }
        });

        /*
         * §10 prefers a state over a delete, and this enforces it. A
         * deleted review takes its moderation history with it, and an
         * appeal about a review nobody can find is unanswerable.
         */
        self::deleting(function (): never {
            throw new RuntimeException(
                'product_reviews is not deleted: withdraw or reject the review instead.'
            );
        });
    }

    /** @return BelongsTo<Product, $this> */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    /** @return HasMany<ProductReviewEvent, $this> */
    public function events(): HasMany
    {
        return $this->hasMany(ProductReviewEvent::class);
    }

    public function countsTowardRating(): bool
    {
        return $this->status->isPublic();
    }
}
