<?php

declare(strict_types=1);

namespace App\Modules\Payments\Models;

use App\Modules\Payments\Enums\PaymentStatus;
use App\Support\HasPublicId;
use Database\Factories\PaymentAttemptFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use RuntimeException;

/**
 * APPEND ONLY. Every attempt is a row, failures included — a customer
 * retrying three times produces three rows against one order, which is what
 * lets support answer "did it charge?" without opening the provider.
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $marketplace_order_id
 * @property string $provider
 * @property string|null $provider_reference
 * @property string|null $method
 * @property string $currency
 * @property int $amount_minor
 * @property PaymentStatus $status
 * @property string|null $failure_code
 * @property string|null $failure_message
 * @property array<string, mixed>|null $raw_response
 * @property Carbon|null $created_at
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 * @property int $id
 * @property string $public_id
 * @property int $marketplace_order_id
 * @property string $provider
 * @property string|null $provider_reference
 * @property string|null $method
 * @property string $currency
 * @property int $amount_minor
 * @property PaymentStatus $status
 * @property string|null $failure_code
 * @property string|null $failure_message
 * @property array<string, mixed>|null $raw_response
 * @property Carbon|null $created_at
 */
final class PaymentAttempt extends Model
{
    /** @use HasFactory<PaymentAttemptFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'payment_attempts';

    public $timestamps = false;

    protected $fillable = [
        'marketplace_order_id', 'provider', 'provider_reference', 'method',
        'currency', 'amount_minor', 'status', 'failure_code', 'failure_message',
        'raw_response', 'created_at',
    ];

    protected function casts(): array
    {
        return [
            'status' => PaymentStatus::class,
            'amount_minor' => 'integer',
            'raw_response' => 'array',
            'created_at' => 'datetime',
        ];
    }

    protected static function booted(): void
    {
        self::deleting(function (): never {
            throw new RuntimeException('payment_attempts is append-only.');
        });
    }
}
