<?php

declare(strict_types=1);

namespace App\Modules\Stores\Models;

use App\Modules\Sellers\Concerns\BelongsToSellerAccount;
use App\Modules\Sellers\Models\SellerAccount;
use App\Support\HasPublicId;
use Database\Factories\StoreFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;

/**
 * Columns, generated by tools/annotate-models.php from the schema.
 *
 * @property int $id
 * @property string $public_id
 * @property int $seller_account_id
 * @property string $name
 * @property string $slug
 * @property string|null $description
 * @property string|null $logo_media_id
 * @property string|null $banner_media_id
 * @property string|null $support_email
 * @property string|null $support_phone
 * @property string|null $shipping_policy
 * @property string|null $return_policy
 * @property bool $is_open
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 *
 * Columns, generated by tools/annotate-models.php from the schema.
 * @property int $id
 * @property string $public_id
 * @property int $seller_account_id
 * @property string $name
 * @property string $slug
 * @property string|null $description
 * @property string|null $logo_media_id
 * @property string|null $banner_media_id
 * @property string|null $support_email
 * @property string|null $support_phone
 * @property string|null $shipping_policy
 * @property string|null $return_policy
 * @property bool $is_open
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property string|null $timezone
 * @property string|null $business_city
 * @property string|null $business_state
 * @property string|null $business_country
 * @property-read SellerAccount|null $sellerAccount
 */
final class Store extends Model
{
    use BelongsToSellerAccount;

    /** @use HasFactory<StoreFactory> */
    use HasFactory;

    use HasPublicId;

    protected $table = 'stores';

    protected $fillable = [
        'seller_account_id',
        'name',
        'slug',
        'description',
        'support_email',
        'support_phone',
        'shipping_policy',
        'return_policy',
        'is_open',
    ];

    protected function casts(): array
    {
        return ['is_open' => 'boolean'];
    }

    /** @return BelongsTo<SellerAccount, $this> */
    public function sellerAccount(): BelongsTo
    {
        return $this->belongsTo(SellerAccount::class);
    }

    /** Slugs a store used before; each one 301s to the current URL forever. */
    public const RESERVED_SLUGS = [
        'admin', 'api', 'seller', 'sellers', 'checkout', 'cart', 'search',
        'store', 'stores', 'account', 'orders', 'login', 'register', 'c', 'p',
    ];
}
